package responses

type FPDFAnnot_IsSupportedSubtype struct{}
type FPDFPage_CreateAnnot struct{}
type FPDFPage_GetAnnotCount struct{}
type FPDFPage_GetAnnot struct{}
type FPDFPage_GetAnnotIndex struct{}
type FPDFPage_CloseAnnot struct{}
type FPDFPage_RemoveAnnot struct{}
type FPDFAnnot_GetSubtype struct{}
type FPDFAnnot_IsObjectSupportedSubtype struct{}
type FPDFAnnot_UpdateObject struct{}
type FPDFAnnot_AddInkStroke struct{}
type FPDFAnnot_RemoveInkList struct{}
type FPDFAnnot_AppendObject struct{}
type FPDFAnnot_GetObjectCount struct{}
type FPDFAnnot_GetObject struct{}
type FPDFAnnot_RemoveObject struct{}
type FPDFAnnot_SetColor struct{}
type FPDFAnnot_GetColor struct{}
type FPDFAnnot_HasAttachmentPoints struct{}
type FPDFAnnot_SetAttachmentPoints struct{}
type FPDFAnnot_AppendAttachmentPoints struct{}
type FPDFAnnot_CountAttachmentPoints struct{}
type FPDFAnnot_GetAttachmentPoints struct{}
type FPDFAnnot_SetRect struct{}
type FPDFAnnot_GetRect struct{}
type FPDFAnnot_GetVertices struct{}
type FPDFAnnot_GetInkListCount struct{}
type FPDFAnnot_GetInkListPath struct{}
type FPDFAnnot_GetLine struct{}
type FPDFAnnot_SetBorder struct{}
type FPDFAnnot_GetBorder struct{}
type FPDFAnnot_HasKey struct{}
type FPDFAnnot_GetValueType struct{}
type FPDFAnnot_SetStringValue struct{}
type FPDFAnnot_GetStringValue struct{}
type FPDFAnnot_GetNumberValue struct{}
type FPDFAnnot_SetAP struct{}
type FPDFAnnot_GetAP struct{}
type FPDFAnnot_GetLinkedAnnot struct{}
type FPDFAnnot_GetFlags struct{}
type FPDFAnnot_SetFlags struct{}
type FPDFAnnot_GetFormFieldFlags struct{}
type FPDFAnnot_GetFormFieldAtPoint struct{}
type FPDFAnnot_GetFormFieldName struct{}
type FPDFAnnot_GetFormFieldType struct{}
type FPDFAnnot_GetFormFieldValue struct{}
type FPDFAnnot_GetOptionCount struct{}
type FPDFAnnot_GetOptionLabel struct{}
type FPDFAnnot_IsOptionSelected struct{}
type FPDFAnnot_GetFontSize struct{}
type FPDFAnnot_IsChecked struct{}
type FPDFAnnot_SetFocusableSubtypes struct{}
type FPDFAnnot_GetFocusableSubtypesCount struct{}
type FPDFAnnot_GetFocusableSubtypes struct{}
type FPDFAnnot_GetLink struct{}
type FPDFAnnot_GetFormControlCount struct{}
type FPDFAnnot_GetFormControlIndex struct{}
type FPDFAnnot_GetFormFieldExportValue struct{}
type FPDFAnnot_SetURI struct{}
