package requests

type FPDFDOC_InitFormFillEnvironment struct{}
type FPDFDOC_ExitFormFillEnvironment struct{}
type FORM_OnAfterLoadPage struct{}
type FORM_OnBeforeClosePage struct{}
type FORM_DoDocumentJSAction struct{}
type FORM_DoDocumentOpenAction struct{}
type FORM_DoDocumentAAction struct{}
type FORM_DoPageAAction struct{}
type FORM_OnMouseMove struct{}
type FORM_OnMouseWheel struct{}
type FORM_OnFocus struct{}
type FORM_OnLButtonDown struct{}
type FORM_OnRButtonDown struct{}
type FORM_OnLButtonUp struct{}
type FORM_OnRButtonUp struct{}
type FORM_OnLButtonDoubleClick struct{}
type FORM_OnKeyDown struct{}
type FORM_OnKeyUp struct{}
type FORM_OnChar struct{}
type FORM_GetFocusedText struct{}
type FORM_GetSelectedText struct{}
type FORM_ReplaceSelection struct{}
type FORM_SelectAllText struct{}
type FORM_CanUndo struct{}
type FORM_CanRedo struct{}
type FORM_Undo struct{}
type FORM_Redo struct{}
type FORM_ForceToKillFocus struct{}
type FORM_GetFocusedAnnot struct{}
type FORM_SetFocusedAnnot struct{}
type FPDFPage_HasFormFieldAtPoint struct{}
type FPDFPage_FormFieldZOrderAtPoint struct{}
type FPDF_SetFormFieldHighlightColor struct{}
type FPDF_SetFormFieldHighlightAlpha struct{}
type FPDF_RemoveFormFieldHighlight struct{}
type FPDF_FFLDraw struct{}
type FPDF_GetFormType struct{}
type FORM_SetIndexSelected struct{}
type FORM_IsIndexSelected struct{}
type FPDF_LoadXFA struct{}
